# .github/workflows/railway-flap.yml
name: Railway Service Flapping

on:
  schedule:
    # 매 5분마다 실행
    - cron: '*/5 * * * *'

jobs:
  control:
    runs-on: ubuntu-latest
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      PROJECT_ID:        ${{ secrets.RAILWAY_PROJECT_ID }}
      SERVICE_IDS:       ${{ secrets.RAILWAY_SERVICE_IDS }}  # "svc1,svc2,svc3" 형태

    steps:
      - name: Railway CLI 설치
        run: npm install -g @railway/cli

      - name: 서비스 플랩(끄고→켜기)
        run: |
          # Railway CLI는 RAILWAY_API_TOKEN 환경변수로 인증
          for SERVICE_ID in $(echo $SERVICE_IDS | tr ',' ' '); do
            echo "▶ 서비스 중지: $SERVICE_ID"
            railway stop --project $PROJECT_ID --service $SERVICE_ID || true
            echo "▶ 서비스 시작: $SERVICE_ID"
            railway up   --project $PROJECT_ID --service $SERVICE_ID --detach
          done