name: Railway Service Schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # KST 09:00
    - cron: '0 10 * * *'  # KST 19:00

jobs:
  control:
    runs-on: ubuntu-latest
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      PROJECT_ID:        ${{ secrets.RAILWAY_PROJECT_ID }}
      SERVICE_IDS:       ${{ secrets.RAILWAY_SERVICE_IDS }}  # "svc1,svc2,svc3" 형태

    steps:
      - name: Railway CLI 설치
        run: npm install -g @railway/cli

      - name: 서비스 플랩(끄고→켜기)
        run: |
          HOUR=$(date +'%H')
          echo "현재 UTC 시간: $HOUR"
          for SERVICE_ID in $(echo $SERVICE_IDS | tr ',' ' '); do
            echo "▶ 서비스 중지: $SERVICE_ID"
            railway link -p $PROJECT_ID -s $SERVICE_ID
            railway down --yes || true
            fi
          done