name: Railway Service Schedule
on:
  workflow_dispatch:
  schedule:
    # UTC 00:00 → KST 09:00, 월~금에만 서비스 시작
    - cron: '0 0 * * 1-5'
    # UTC 10:00 → KST 19:00, 월~금에만 서비스 종료
    - cron: '0 10 * * 1-5'

jobs:
  control:
    runs-on: ubuntu-latest
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      PROJECT_ID:        ${{ secrets.RAILWAY_PROJECT_ID }}
      SERVICE_IDS:       ${{ secrets.RAILWAY_SERVICE_IDS }}  # "svc1,svc2,svc3" 형태

    steps:
      - name: Railway CLI 설치
        run: npm install -g @railway/cli

      - name: 서비스 플랩(끄고→켜기)
        run: |
          # Railway CLI는 RAILWAY_API_TOKEN 환경변수로 인증
          for SERVICE_ID in $(echo $SERVICE_IDS | tr ',' ' '); do
            echo "▶ 서비스 중지: $SERVICE_ID"
            railway stop --project $PROJECT_ID --service $SERVICE_ID || true
            echo "▶ 서비스 시작: $SERVICE_ID"
            railway up   --project $PROJECT_ID --service $SERVICE_ID --detach
          done